## This file has been generated by a Large Language Model
#!/bin/bash

# E-Learning API Test Script
# Run with: ./test-api.sh

BASE_URL="http://localhost:8080"
PASS=0
FAIL=0

# Colors
GREEN='\033[0;32m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo "========================================"
echo "   E-Learning API Test Suite"
echo "========================================"
echo ""

test_endpoint() {
  local method=$1
  local endpoint=$2
  local data=$3
  local description=$4

  echo -e "${BLUE}Testing:${NC} $description"
  echo "  $method $endpoint"

  if [ "$method" == "GET" ]; then
    response=$(curl -s -w "\n%{http_code}" "$BASE_URL$endpoint")
  else
    response=$(curl -s -w "\n%{http_code}" -X $method "$BASE_URL$endpoint" \
      -H "Content-Type: application/json" \
      -d "$data")
  fi

  http_code=$(echo "$response" | tail -n1)
  body=$(echo "$response" | sed '$d')

  if [ "$http_code" == "200" ]; then
    echo -e "  ${GREEN}✓ PASS${NC} (HTTP $http_code)"
    ((PASS++))
  else
    echo -e "  ${RED}✗ FAIL${NC} (HTTP $http_code)"
    echo "  Response: $body"
    ((FAIL++))
  fi
  echo ""
}

echo "========== USER MANAGEMENT =========="
test_endpoint "GET" "/students" "" "#1 List all students"
test_endpoint "GET" "/students/1" "" "#1 Get student by ID"
test_endpoint "GET" "/students/1/courses" "" "#14 View student's courses"

echo "========== COURSE MANAGEMENT =========="
test_endpoint "GET" "/courses" "" "#2 List all courses"
test_endpoint "GET" "/courses/1" "" "#2 Get course by ID"

echo "========== ENROLLMENTS =========="
test_endpoint "GET" "/enrollments/1" "" "#4 Get student enrollments"

echo "========== SUBMISSIONS =========="
test_endpoint "GET" "/submissions/assignment/1" "" "#10 View submissions"

echo "========== QUIZ ATTEMPTS =========="
test_endpoint "GET" "/quiz-attempts/1/1" "" "#9 View quiz attempts"

echo "========== FORUM POSTS =========="
test_endpoint "GET" "/posts/forum/1" "" "#11 View forum posts"

echo "========== REPORTS =========="
test_endpoint "GET" "/reports/grades/1" "" "#12 Student grade report"
test_endpoint "GET" "/reports/gpa/1" "" "#13 Student GPA"
test_endpoint "GET" "/reports/roster/1/1" "" "#15 Class roster"
test_endpoint "GET" "/reports/missing-submissions/1" "" "#16 Missing submissions"
test_endpoint "GET" "/reports/enrollment-stats" "" "#17 Enrollment statistics"
test_endpoint "GET" "/reports/quiz-stats/1" "" "#18 Quiz performance"
test_endpoint "GET" "/reports/at-risk/1?threshold=70" "" "#19 At-risk students"
test_endpoint "GET" "/reports/instructor-workload" "" "#20 Instructor workload"
test_endpoint "GET" "/reports/forum-activity/1" "" "#21 Forum activity"
test_endpoint "GET" "/reports/platform-activity?start=2025-01-01&end=2025-12-31" "" "#22 Platform activity"

echo "========== POST OPERATIONS =========="
test_endpoint "POST" "/courses" '{"title":"Test Course","description":"Test","credits":3}' "#2 Create course"
test_endpoint "POST" "/assignments" '{"course_id":1,"section_number":1,"title":"Test HW","max_points":100}' "#6 Create assignment"
test_endpoint "POST" "/quizzes" '{"course_id":1,"section_number":1,"title":"Test Quiz","total_points":50,"attempt_limit":3}' "#8 Create quiz"

echo "========================================"
echo "   TEST SUMMARY"
echo "========================================"
echo -e "  ${GREEN}Passed:${NC} $PASS"
echo -e "  ${RED}Failed:${NC} $FAIL"
echo "========================================"

if [ $FAIL -eq 0 ]; then
  echo -e "${GREEN}All tests passed!${NC}"
  exit 0
else
  echo -e "${RED}Some tests failed.${NC}"
  exit 1
fi
