name:                elearning-backend-api
version:             0.1.0.0
github:              "suren-manukyan-aua/elearning-backend-api"
license:             BSD-3-Clause
author:              "Suren Manukyan"
maintainer:          "suren_manukyan@edu.aua.am"
copyright:           "2025 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/suren-manukyan-aua/elearning-backend-api#readme>

dependencies:
- base >= 4.7 && < 5
- servant-server
- warp
- aeson
- postgresql-simple
- text
- time
- bytestring
- mtl
- resource-pool
- scientific

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  elearning-backend-api-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - elearning-backend-api

tests:
  elearning-backend-api-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - elearning-backend-api
